import {NextPageContext} from 'next'

import Head from "next/head"
// import Image from "next/image"
import Header from "@components/header"

export default function Home({data}:any) {

  console.log(data)
  
  return (
    <>
      <Head>
        <title>Friendly Mini Chat</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        <Header />
      </main>
    </>
  )
}

export  async function getStaticProps(ctx: NextPageContext) {

const ROOT_URL = process.env.NEXT_PUBLIC_VERCEL_URL || 'localhost:8000'


const res  = await fetch(`http://${ROOT_URL}/api/rooms`)
const response = await res.json()

  return {
    props: {
      data: response
    }
  }
}

